#!/usr/bin/env zsh
echo "Setting up yabai"

# Get the path to the user-specific configuration files
yabai_config_path="${XDG_CONFIG_HOME:-$HOME/.config}/yabai"
# Install yabai using Homebrew
brew install koekeishiya/formulae/yabai

echo "yabai installed, starting service..."
# Start yabai, if not used before may need to grant permission in Privacy & Security -> Accessibility 
yabai --start-service


# Check if the configuration directory exists, if not create it
if [[ ! -d "$yabai_config_path" ]]; then
    mkdir -p "$yabai_config_path"
    echo "Directory $yabai_config_path created."
else
    echo "Directory $yabai_config_path already exists."
fi

touch ${yabai_config_path}/yabairc
chmod +x ${yabai_config_path}/yabairc

    
    cat <<EOF > "${yabai_config_path}/yabairc"
# enable debug info to stdout
yabai -m config debug_output on
yabai -m config layout bsp
yabai -m config window_placement second_child

# padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# when focusing a windoe put th emouse at its center
yabai -m config mouse_follows_focus on

# Keyboard modifier used for moving and resizing windows
yabai -m config mouse_modifier alt

# Action performed when pressed mouse_modifier + button1
yabai -m config mouse_action1 move
# Action performed when pressed mouse_modifier + button2
yabai -m config mouse_action2 resize

# Action performed when a bsp-managed window is dropped in the center of some other bsp-managed window.
yabai -m mouse_drop_action swap

EOF







    

